### ISSUE TITLE
Exception when no results for a query

### ISSUE THREAD

**Issue by johnkangcurd** [dmmikkel/harvestclient#4]
Hi @dmmikkel!  Your harvest client has been a huge time saver.  I was just wondering if you encountered any issues when querying and the API returning an empty result set?  

For instance, if I query for all tasks updated since today when I know that nothing has been updated since today, I get the following exception:

`com.enonic.harvest.harvestclient.exceptions.HarvestClientException: Unable to parse XML into ClientCollection.
    at com.enonic.harvest.harvestclient.models.ClientCollection.fromInputStream(ClientCollection.java:45) ~[harvestclient-0.1-SNAPSHOT.jar:na]
    at com.enonic.harvest.harvestclient.DefaultHarvestClient.getClients(DefaultHarvestClient.java:88) ~[harvestclient-0.1-SNAPSHOT.jar:na]
    at com.vcg.harvest.collector.HarvestCollector.collect(HarvestCollector.java:92) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"nil-classes"). Expected elements are <{}client>,<{}clients>
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:357) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:614) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3135) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.8.0_72]
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243) ~[na:1.8.0_72]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214) ~[na:1.8.0_72]
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.8.0_72]
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204) ~[na:1.8.0_72]
    at com.enonic.harvest.harvestclient.models.ClientCollection.fromInputStream(ClientCollection.java:41) ~[harvestclient-0.1-SNAPSHOT.jar:na]
    ... 15 common frames omitted
`

**Comment by johnkangcurd** [comment]
I also opened a ticket with Harvest a this could totally be due to an inconsistency in the XML messages being returned by the Harvest services themselves (which I'm digging into outside of the context of the Harvest Client).

**Comment by dmmikkel** [comment]
Hi,

I am glad that you found it useful. I do unfortunately not have any time to
fix bugs or keep it updated. I hope you are able to resolve this :)

Mvh / Best regards,
Dag Martin Mikkelsen

**Comment by umarsaeed7** [comment]
will you update TaskAssignment?

Need to change 
From     @XmlElement(name = "hourlyRate")
To          @XmlElement(name = "hourly-rate")

**Comment by johnkangcurd** [comment]
@umarsaeed7 not really the best place to ask for this.  I would suggest opening another issue; however, I think @dmmikkel has expressed he doesn't have time to update/fix bugs.  No worries because he did most of the heavy lifting and really does a lot for us.  We should all be thankful.

Suggestions:
1. You could fork the project and make the change yourself
2. Use my fork.  It has the same model but doesn't use the XXXcollection types (just uses your plain ole Java collections).  It also doesn't throw a harvestclientexception whenever an empty collection is returned by Harvest's API (because the Harvest API's xml document is not consistent).  My client fork uses JSON instead of XML.  Anywho, enough chatter; check it out here: https://github.com/johnkangcurd/harvestclient

**Comment by johnkangcurd** [comment]
Closing this as I understand @dmmikkel 's time constraints don't allow for changes/bug fixes.  

Should anyone else be interested in some changes: check out my fork for another option: https://github.com/johnkangcurd/harvestclient
